# Generated by Django 5.0.7 on 2024-08-06 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='No Bio')),
                ('profile_image', models.ImageField(default='default_profile.png', upload_to='profile_images')),
                ('linkedin_id', models.CharField(blank=True, default='s', max_length=120, null=True)),
                ('instagram_id', models.CharField(blank=True, default='s', max_length=120, null=True)),
                ('telegram_id', models.CharField(blank=True, default='s', max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='account.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
