# Generated by Django 5.0.7 on 2024-08-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maziar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('music', 'music'), ('programming', 'programming'), ('life', 'life'), ('studies', 'studies')], default='music', max_length=40)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='post_image_files')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='post_video_files')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='post_audio_files')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
